version: '3.8'

services:
  client-service:
    image: timeslot-client-service
    environment:
      - PORT=3000
    network_mode: "host"

  email-service:
    image: timeslot-email-service
    environment:
      - PORT=3001
    network_mode: "host"

  google-service:
    image: timeslot-google-service
    environment:
      - PORT=3002
    network_mode: "host"

  user-service:
    image: timeslot-user-service
    environment:
      - PORT=3003
    depends_on:
      - redis
    network_mode: "host"

  redis:
    image: redis:latest
    network_mode: "host"


